### PR TITLE
Disable f-string warning in .pylintrc

### PR DESCRIPTION
**Pull request by tekktrik**
New black version didn't want the f-strings, and this library is used widely enough that it does need to be

### CODE REVIEW

**Comment by kattni** [comment]
This should be disabled in the .pre-commit-config.yaml file, not .pylintrc.

**Comment by tekktrik** [comment]
It looks like it is though, unless I'm not understanding correctly

**Comment by tekktrik** [comment]
```
        args: ['([[ ! -d "examples" ]] || for example in $(find . -path "./examples/*.py"); do pylint --disable=missing-docstring,invalid-name,consider-using-f-string $example; done)']
```

**Comment by tekktrik** [comment]
Never mind, those are the examples

**Comment by tekktrik** [comment]
Closing in favor of #20

**Pull request closed without merging**
